language: haskell

ghc:
  - 7.8

before_install:
  - cabal install doctest

script:
  - cabal configure --enable-tests
  - cabal build
  - cabal test
  - doctest src/*.hs
  - cabal haddock --executables
  - cabal check
